Feature/catalog
andreiokcober/chebProSport pull request #3
Opened 2023-06-30 10:23 UTC by andreiokcober

2023-06-30 16:11 UTC, SergeyObodovskiy requested changes

2023-06-30 16:11 UTC, SergeyObodovskiy commented on chebProSport/src/App.tsx
>          <main style={{ backgroundColor: '#F7F0F5', padding: '40px 0px' }}>
Лучше задать класс и перенести стили отсюда в файл со стилями

2023-06-30 16:11 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/cards.tsx
> +const CardsContainer = () => {
Если ты возвращаешь только разметку, то можно писать красивее:
```
const CardsContainer = () => (
    <Grid container spacing={3} sx={{ paddingTop: '20px' }}>
      {ImageCatalog.map((item, i) => (
        <Item item={item} key={i}></Item>
      ))}
    </Grid>
  )
```

2023-06-30 16:11 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +  const { name } = prop;
Лучше деструктуризацию делать в одну строку:
```
const { name, content } = prop;
```

2023-06-30 16:11 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +    const svg = event.currentTarget.querySelector('.svg-button-catalog');
Так делать не надо, надо использовать useRef
https://legacy.reactjs.org/docs/hooks-reference.html#useref
https://react.dev/reference/react/useRef

2023-07-02 13:34 UTC, andreiokcober commented on chebProSport/src/components/catalog/cards.tsx
> +const CardsContainer = () => {
не совсем понял, как лучше нужно здесь написать)

2023-07-04 09:40 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/cards.tsx
> +const CardsContainer = () => {
Если ты в функции(компоненте) ничего не делаешь, а просто возвращаешь что-нибудь, то можно писасть проще:  **const foo = (value) => value** или **const foo = () => 'just a string'**

2023-07-04 09:40 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/cards.tsx
> +const CardsContainer = () => {
то есть тебе надо просто скопировать этот вариант:
```
const CardsContainer = () => (
    <Grid container spacing={3} sx={{ paddingTop: '20px' }}>
      {ImageCatalog.map((item, i) => (
        <Item item={item} key={i}></Item>
      ))}
    </Grid>
  )
  ```

2023-07-04 10:02 UTC, SergeyObodovskiy requested changes

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +  const [openButton, setOpenButton] = useState<string>('none');
Если у тебя по сути только два значения, то проще и яснее использовать булево - true/false

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +  const [openButton, setOpenButton] = useState<string>('none');
тогда будет:
```
const [isOpenButton, setIsOpenButton] = useState<boolean>(false);
```

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +    if (openButton === 'block') {
а здесь:
```
  const handleClickButton = () => {
    if (isOpenButton){
      svg.current?.classList.remove('svg-button-catalog-show');
      setIsOpenButton(false);
    } else {
      setIsOpenButton(true);
      svg.current?.classList.add('svg-button-catalog-show');
    }
  };
```

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +              <>
здесь нет необходимости использовать обертку фрагмента - у тебя один дочерний элемент внутри, а не два и более. Можешь удалить

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +        <>
здесь нет необходимости использовать обертку фрагмента - у тебя один дочерний элемент внутри, а не два и более. Можешь удалить

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +      {content && openButton === 'block' ? (
будет:
```
      {content && isOpenButton && (
```

2023-07-04 10:02 UTC, SergeyObodovskiy commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +      ) : (
можно удалить это:
```
 : (
        ''
      )}
```

2023-07-04 14:16 UTC, andreiokcober commented on chebProSport/src/components/catalog/catalogMenu/button.tsx
> +  const [openButton, setOpenButton] = useState<string>('none');
Так и хотел делать
Изначально не правильно указал тип useState<Boolean>(false)

2023-07-04 14:59 UTC, SergeyObodovskiy approved these changes

2023-07-04 14:59 UTC, merged